name: Build & Deploy Spring app

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy Spring boot for beginner
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: jdbc:postgresql://localhost:5432/moviedb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Ajuuke@01
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build the application
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/moviedb
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: Ajuuke@01
        run: |
          mvn clean
          mvn -B package --file pom.xml
          
