name: Build & Deploy Spring app

on:
  push:
    branches:
      - master
      - dev   # 👈 also trigger on dev branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    # 👇 choose environment based on branch
    # environment: ${{ github.ref == 'refs/heads/master' && 'prod' || 'dev' }}
    # Note: The above line is commented out because GitHub Actions does not support conditional environment names directly.

    env:
      DATASOURCE.URL: ${{ secrets.DB_URL }}
      DATASOURCE.USERNAME: ${{ secrets.DB_USERNAME }}
      DATASOURCE.PASSWORD: ${{ secrets.DB_PASSWORD }}
      FRONTEND_URL: https://localhost:3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build the application
        run: mvn clean package -B --file pom.xml

          
